## HPC Lab-1 
Name: Tanvi Penumudy

Enroll No: E18CSE187 

Demo Code-I

In [5]:
# Python program to illustrate the concept of threading 
import threading 
import os 

def task1(): 
  print("Task 1 assigned to thread: {}".format(threading.current_thread().name)) 
  print("ID of process running task 1: {}".format(os.getpid())) 

def task2(): 
  print("Task 2 assigned to thread: {}".format(threading.current_thread().name)) 
  print("ID of process running task 2: {}".format(os.getpid())) 

if __name__ == "__main__": 

  # print ID of current process 
  print("ID of process running main program: {}".format(os.getpid())) 

  # print name of main thread 
  print("Main thread name: {}".format(threading.current_thread().name)) 

  # creating threads 
  t1 = threading.Thread(target=task1, name='t1') 
  t2 = threading.Thread(target=task2, name='t2') 

  # starting threads Spawn
  t1.start() 
  t2.start() 

  # wait until all threads finish Sync
  t1.join() 
  t2.join() 

ID of process running main program: 1944
Main thread name: MainThread
Task 1 assigned to thread: t1
ID of process running task 1: 1944
Task 2 assigned to thread: t2
ID of process running task 2: 1944


Demo Code-II

In [7]:
# importing the multiprocessing module 
import multiprocessing 
import os 

def worker1(): 
  # printing process id 
  print("ID of process running worker1: {}".format(os.getpid())) 
  for i in range(100):
    print("P1",i)

def worker2(): 
  # printing process id 
  print("ID of process running worker2: {}".format(os.getpid()))
  for i in range(100):
    print("P2",i)  

if __name__ == "__main__": 
  # printing main program process id 
  print("ID of main process: {}".format(os.getpid())) 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2) 

  # starting processes 
  p1.start() 
  p2.start() 

  # process IDs 
  print("ID of process p1: {}".format(p1.pid)) 
  print("ID of process p2: {}".format(p2.pid)) 

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print("Both processes finished execution!") 

  # check if processes are alive 
  print("Process p1 is alive: {}".format(p1.is_alive())) 
  print("Process p2 is alive: {}".format(p2.is_alive())) 

ID of main process: 1944
ID of process running worker1: 1969
ID of process running worker2: 1970
P1 0
P2 0
P1 1
P2 1
P2 2
P2 3
P1 2
P1 3
P2 4
P1 4
P2 5
P1 5
P2 6
P1 6
P1 7
P1 8
P2 7
P1 9
P2 8
P1 10
P2 9
P2 10
P2 11
P2 12
P1 11
P1 12
P1 13
P2 13
P1 14
P2 14
P1 15
P2 15
P2 16
P2 17
P1 16
P2 18
P2 19
P1 17
P2 20
P1 18
P1 19
P2 21
P1 20
P1 21
P1 22
P2 22
P2 23
P2 24
P1 23
P1 24
P2 25
P1 25
P1 26
P1 27
P2 26
P2 27
P1 28
P2 28
P1 29
P1 30
P1 31
P1 32
P2 29
P2 30
P2 31
P1 33
P1 34
P2 32
P1 35
P2 33
P1 36
ID of process p1: 1969
ID of process p2: 1970
P2 34
P1 37
P2 35
P1 38
P1 39
P2 36
P1 40
P2 37
P1 41
P1 42
P1 43
P1 44
P1 45
P1 46
P2 38
P1 47
P2 39
P2 40
P2 41
P1 48
P2 42
P2 43
P2 44
P1 49
P2 45
P2 46
P2 47
P1 50
P2 48
P1 51
P2 49
P2 50
P1 52
P2 51
P1 53
P2 52
P2 53
P1 54
P1 55
P1 56
P1 57
P1 58
P1 59
P2 54
P1 60
P2 55
P2 56
P2 57
P2 58
P1 61
P2 59
P1 62
P2 60
P1 63
P2 61
P2 62
P2 63
P1 64
P2 64
P1 65
P1 66
P2 65
P1 67
P1 68
P1 69
P1 70
P2 66
P1 71
P1 72
P1 73
P1 74
P1 75
P2 67
P2 68
P2 69
P

## 1. Matrix Multiplication

In [15]:
# Creating random integer arrays (without numpy)
import random
X = [random.choices(range(9,999), k=4) for _ in range(4)]
Y = [random.choices(range(9,999), k=4) for _ in range(4)]
result = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]

In [52]:
print(X)
print(Y)
print(result)

[[969, 321, 191, 83], [308, 521, 74, 204], [134, 172, 456, 723], [178, 850, 278, 911]]
[[509, 620, 746, 958], [75, 34, 516, 312], [246, 943, 125, 24], [631, 798, 580, 285]]
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [53]:
X[:2]

[[969, 321, 191, 83], [308, 521, 74, 204]]

In [54]:
X[2:]

[[134, 172, 456, 723], [178, 850, 278, 911]]

In [55]:
import time

In [56]:
%%time
# Serial - Explicit loops
for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

print(result)

[[616655, 858041, 960525, 1056693], [342775, 441248, 626174, 517532], [649495, 1095890, 665056, 399035], [797581, 1128392, 1134518, 702031]]
CPU times: user 100 µs, sys: 871 µs, total: 971 µs
Wall time: 1.23 ms


In [59]:
%%time
# Parallel - Explicit loops
def worker1(X, Y, result): 
  for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
  return result

def worker2(X, Y, result):
  for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
  return result
  
if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print(worker1(X[:2],Y,[[0,0,0,0],[0,0,0,0]]))
  print(worker2(X[2:],Y,[[0,0,0,0],[0,0,0,0]]))
  print("Done!") 

Process Process-15:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Process Process-16:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker1() missing 3 required positional arguments: 'X', 'Y', and 'result'
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker2() missing 3 required positional arguments: 'X', 'Y', and 'result'


[[616655, 858041, 960525, 1056693], [342775, 441248, 626174, 517532]]
[[649495, 1095890, 665056, 399035], [797581, 1128392, 1134518, 702031]]
Done!
CPU times: user 9.28 ms, sys: 14 ms, total: 23.3 ms
Wall time: 53.7 ms


In [61]:
import numpy as np

In [62]:
A = np.random.randint(9,999,(4,4))
B = np.random.randint(9,999,(4,4))
A

array([[522, 707, 208, 996],
       [419, 226, 783, 394],
       [902, 813, 729, 473],
       [375, 190, 822, 838]])

In [63]:
B

array([[338, 539, 423, 292],
       [919, 964, 614, 388],
       [669, 213, 392, 678],
       [211, 415, 379, 557]])

In [64]:
%%time
# Serial - Using Numpy
print(np.dot(A,B))

[[1175477 1420550 1113924 1122536]
 [ 956277  773994  772263  960368]
 [1639527 1621482 1345763 1336551]
 [1028096  908141  915111 1207302]]
CPU times: user 756 µs, sys: 0 ns, total: 756 µs
Wall time: 764 µs


In [65]:
%%time
# Parallel - Using Numpy
def worker1(A, B): 
  result = np.dot(A,B)
  return result

def worker2(A, B):
  result = np.dot(A,B)
  return result
  
if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print(worker1(A[:2],B))
  print(worker2(A[2:],B))
  print("Done!") 

Process Process-17:
Process Process-18:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker1() missing 2 required positional arguments: 'A' and 'B'
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker2() missing 2 required positional arguments: 'A' and 'B'


[[1175477 1420550 1113924 1122536]
 [ 956277  773994  772263  960368]]
[[1639527 1621482 1345763 1336551]
 [1028096  908141  915111 1207302]]
Done!
CPU times: user 14.1 ms, sys: 11.6 ms, total: 25.7 ms
Wall time: 66.1 ms


In [66]:
A = np.random.uniform(9,999,[4,4])
B = np.random.uniform(9,999,[4,4])
A

array([[799.39480627, 544.21267013, 324.79167802, 880.40943167],
       [684.98434019, 436.59281634,  13.75165586,  80.82904175],
       [774.16870956,  22.84637019, 951.88006269, 806.60249314],
       [731.58017174, 794.51618272, 220.51994599, 664.06568702]])

In [67]:
B

array([[ 14.94682735, 648.95453752, 985.11577827, 628.5825784 ],
       [640.61910265, 972.61022246, 841.32313336, 313.73063193],
       [ 38.14433689, 882.5159774 , 293.40730424, 448.76434794],
       [ 56.44711806, 769.93675768, 126.15568471, 306.56098512]])

In [68]:
%%time
# Serial - Using Random Float
print(np.dot(A,B))

[[ 422666.98685257 2012571.12137775 1451720.05093295 1088875.94167413]
 [ 295015.15514978  943527.63826008 1056336.39701224  598492.04642743]
 [ 108046.4071534  1985703.18225377 1162913.04354993 1168239.26027648]
 [ 565813.22787372 1953417.7908447  1537613.83892556 1011660.73571043]]
CPU times: user 2.24 ms, sys: 30 µs, total: 2.27 ms
Wall time: 10.3 ms


In [69]:
%%time
# Parallel - Using Random Float
def worker1(A, B): 
  result = np.dot(A,B)
  return result

def worker2(A, B):
  result = np.dot(A,B)
  return result
  
if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print(worker1(A[:2],B))
  print(worker2(A[2:],B))
  print("Done!") 

Process Process-19:
Process Process-20:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker1() missing 2 required positional arguments: 'A' and 'B'
TypeError: worker2() missing 2 required positional arguments: 'A' and 'B'


[[ 422666.98685257 2012571.12137775 1451720.05093295 1088875.94167413]
 [ 295015.15514978  943527.63826008 1056336.39701224  598492.04642743]]
[[ 108046.4071534  1985703.18225377 1162913.04354993 1168239.26027648]
 [ 565813.22787372 1953417.7908447  1537613.83892556 1011660.73571043]]
Done!
CPU times: user 10.9 ms, sys: 11.1 ms, total: 22 ms
Wall time: 53.5 ms


In [70]:
A = np.random.randint(9,999,(8,8))
B = np.random.randint(9,999,(8,8))
A

array([[718, 511, 723, 206, 400, 811, 520, 432],
       [878,  59,  95, 487, 859, 578, 542, 962],
       [894, 241, 835, 170, 622,  89, 930, 919],
       [333, 788, 171, 954, 445, 701, 956, 971],
       [917, 182, 453, 712, 989, 488, 829, 224],
       [384, 261, 147, 964, 632, 519, 816, 332],
       [701, 859, 630, 523, 723, 423, 523, 582],
       [510, 280, 362, 980, 202, 957,  20, 531]])

In [71]:
B

array([[415, 293, 125, 414, 636, 402, 209, 847],
       [901, 505, 193, 432, 266, 895,  15, 270],
       [210, 286,  81, 307, 933, 795,  60, 757],
       [519, 421, 464, 397, 107, 879, 861, 702],
       [279, 180, 409, 798, 975, 623, 746,  51],
       [153, 405, 921, 168, 424, 976, 543, 965],
       [146, 557, 153, 817, 516, 318, 448, 170],
       [337, 813, 290, 482, 815, 902, 452, 128]])

In [72]:
%%time
# Serial - Changing Matrix Size to 8*8
print(np.dot(A,B))

[[1474312 1803244 1457891 1910259 2643439 3097600 1545470 2384750]
 [1421653 1991956 1600375 2300568 2861145 3048724 2241702 1990240]
 [1484369 2107189 1049945 2512139 3302986 2987386 1731298 1967062]
 [2077430 2631969 1905700 2631465 2698777 3954898 2492864 2279934]
 [1556312 1809426 1562558 2536464 2911968 3075612 2310013 2359545]
 [1412462 1740586 1515191 2117789 2081841 2811416 2191916 1898008]
 [2007539 2105483 1481203 2418176 2946556 3565729 1913912 2278207]
 [1433216 1673730 1722897 1426548 1887249 3150030 1895605 2474739]]
CPU times: user 556 µs, sys: 10 µs, total: 566 µs
Wall time: 461 µs


In [73]:
%%time
# Parallel - Changing Matrix Size to 8*8
def worker1(A, B): 
  result = np.dot(A,B)
  return result

def worker2(A, B):
  result = np.dot(A,B)
  return result
  
if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print(worker1(A[:4],B))
  print(worker2(A[4:],B))
  print("Done!") 

Process Process-21:
Traceback (most recent call last):
Process Process-22:
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
TypeError: worker1() missing 2 required positional arguments: 'A' and 'B'
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker2() missing 2 required positional arguments: 'A' and 'B'


[[1474312 1803244 1457891 1910259 2643439 3097600 1545470 2384750]
 [1421653 1991956 1600375 2300568 2861145 3048724 2241702 1990240]
 [1484369 2107189 1049945 2512139 3302986 2987386 1731298 1967062]
 [2077430 2631969 1905700 2631465 2698777 3954898 2492864 2279934]]
[[1556312 1809426 1562558 2536464 2911968 3075612 2310013 2359545]
 [1412462 1740586 1515191 2117789 2081841 2811416 2191916 1898008]
 [2007539 2105483 1481203 2418176 2946556 3565729 1913912 2278207]
 [1433216 1673730 1722897 1426548 1887249 3150030 1895605 2474739]]
Done!
CPU times: user 10.9 ms, sys: 13.5 ms, total: 24.4 ms
Wall time: 60.5 ms


In [74]:
# Parallel - Increasing Threads to 4
%%time
def worker1(A, B): 
  result = np.dot(A,B)
  return result

def worker2(A, B):
  result = np.dot(A,B)
  return result

def worker3(A, B): 
  result = np.dot(A,B)
  return result

def worker4(A, B):
  result = np.dot(A,B)
  return result
  
if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)
  p3 = multiprocessing.Process(target=worker3) 
  p4 = multiprocessing.Process(target=worker4)

  # starting processes 
  p1.start() 
  p2.start()
  p3.start() 
  p4.start()

  # wait until processes are finished 
  p1.join() 
  p2.join()
  p3.join() 
  p4.join()  

  # both processes finished 
  print(worker1(A[:2],B))
  print(worker2(A[2:4],B))
  print(worker3(A[4:6],B))
  print(worker4(A[6:],B))
  print("Done!") 

Process Process-24:
Process Process-23:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Process Process-25:
TypeError: worker2() missing 2 required positional arguments: 'A' and 'B'
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
TypeError: worker1() missing 2 required positional arguments: 'A' and 'B'
Process Process-26:
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call 

[[1474312 1803244 1457891 1910259 2643439 3097600 1545470 2384750]
 [1421653 1991956 1600375 2300568 2861145 3048724 2241702 1990240]]
[[1484369 2107189 1049945 2512139 3302986 2987386 1731298 1967062]
 [2077430 2631969 1905700 2631465 2698777 3954898 2492864 2279934]]
[[1556312 1809426 1562558 2536464 2911968 3075612 2310013 2359545]
 [1412462 1740586 1515191 2117789 2081841 2811416 2191916 1898008]]
[[2007539 2105483 1481203 2418176 2946556 3565729 1913912 2278207]
 [1433216 1673730 1722897 1426548 1887249 3150030 1895605 2474739]]
Done!
CPU times: user 13.3 ms, sys: 29.2 ms, total: 42.4 ms
Wall time: 90.2 ms


In [98]:
X = [random.choices(range(9,999), k=8) for _ in range(8)]
Y = [random.choices(range(9,999), k=8) for _ in range(8)]
def zeros(rows,cols):
  return [([0]*cols) for i in range(rows)]

In [99]:
print(X)
print(Y)

[[271, 532, 688, 674, 40, 487, 686, 584], [670, 900, 979, 862, 15, 396, 300, 802], [435, 919, 425, 538, 172, 736, 494, 873], [965, 840, 495, 469, 355, 338, 102, 325], [886, 699, 212, 516, 23, 572, 619, 627], [599, 715, 958, 674, 311, 964, 80, 672], [896, 687, 997, 235, 576, 612, 103, 759], [69, 116, 360, 634, 119, 991, 515, 879]]
[[709, 362, 452, 286, 800, 284, 57, 779], [76, 634, 338, 592, 662, 677, 133, 664], [681, 311, 281, 56, 318, 390, 741, 967], [189, 88, 968, 396, 256, 346, 133, 191], [167, 542, 601, 384, 817, 93, 601, 668], [10, 971, 334, 77, 456, 674, 347, 436], [884, 723, 635, 152, 750, 100, 55, 356], [220, 201, 76, 158, 922, 510, 450, 270]]


In [100]:
# Serial - Changing Matrix Size to 8*8 (Without Numpy)
def seq(X,Y):
  result = zeros(len(X),len(Y[0]))
  for i in range(len(X)):
    for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
  return result

In [101]:
%%time
print(seq(X,Y))

[[1574939, 1816589, 1814760, 947285, 2268012, 1637050, 1179212, 1999335], [1821152, 1964213, 2109286, 1329164, 2821069, 2186961, 1521802, 2736881], [1434206, 2260150, 1876685, 1241048, 2880802, 2104291, 1312285, 2310180], [1398094, 1736786, 1728904, 1215914, 2425867, 1634841, 1078398, 2386309], [1617891, 2016680, 1841382, 1129442, 2693017, 1755400, 897691, 2112300], [1538952, 2324916, 2044807, 1227134, 2802973, 2290374, 1756977, 2834473], [1771192, 2224129, 1818508, 1215738, 3075512, 2053149, 1818230, 3056334], [1101146, 1842057, 1581610, 698795, 2154583, 1636683, 1209714, 1532227]]
CPU times: user 1.28 ms, sys: 35 µs, total: 1.32 ms
Wall time: 5.12 ms


In [103]:
%%time
# Parallel - Changing Matrix Size to 8*8 (Without Numpy)
def worker1(A, B): 
  return seq(A,B)

def worker2(A, B):
  return seq(A,B)
  
if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print(worker1(X[:4],Y))
  print(worker2(X[4:],Y))
  print("Done!") 

Process Process-33:
Traceback (most recent call last):
Process Process-34:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker2() missing 2 required positional arguments: 'A' and 'B'
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker1() missing 2 required positional arguments: 'A' and 'B'


[[1574939, 1816589, 1814760, 947285, 2268012, 1637050, 1179212, 1999335], [1821152, 1964213, 2109286, 1329164, 2821069, 2186961, 1521802, 2736881], [1434206, 2260150, 1876685, 1241048, 2880802, 2104291, 1312285, 2310180], [1398094, 1736786, 1728904, 1215914, 2425867, 1634841, 1078398, 2386309]]
[[1617891, 2016680, 1841382, 1129442, 2693017, 1755400, 897691, 2112300], [1538952, 2324916, 2044807, 1227134, 2802973, 2290374, 1756977, 2834473], [1771192, 2224129, 1818508, 1215738, 3075512, 2053149, 1818230, 3056334], [1101146, 1842057, 1581610, 698795, 2154583, 1636683, 1209714, 1532227]]
Done!
CPU times: user 5.22 ms, sys: 17.8 ms, total: 23 ms
Wall time: 58.7 ms


In [104]:
# Serial - Increasing Threads to 4 (Without Numpy)
%%time
def worker1(A, B): 
  return seq(A, B)

def worker2(A, B):
  return seq(A, B)

def worker3(A, B): 
  return seq(A, B)

def worker4(A, B):
  return seq(A, B)
  
if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)
  p3 = multiprocessing.Process(target=worker3) 
  p4 = multiprocessing.Process(target=worker4)

  # starting processes 
  p1.start() 
  p2.start()
  p3.start() 
  p4.start()

  # wait until processes are finished 
  p1.join() 
  p2.join()
  p3.join() 
  p4.join()  

  # both processes finished 
  print(worker1(X[:2],Y))
  print(worker2(X[2:4],Y))
  print(worker3(X[4:6],Y))
  print(worker4(X[6:],Y))
  print("Done!") 

Process Process-35:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Process Process-36:
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker2() missing 2 required positional arguments: 'A' and 'B'
Process Process-38:
Process Process-37:
TypeError: worker1() missing 2 required positional arguments: 'A' and 'B'
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib

[[1574939, 1816589, 1814760, 947285, 2268012, 1637050, 1179212, 1999335], [1821152, 1964213, 2109286, 1329164, 2821069, 2186961, 1521802, 2736881]]
[[1434206, 2260150, 1876685, 1241048, 2880802, 2104291, 1312285, 2310180], [1398094, 1736786, 1728904, 1215914, 2425867, 1634841, 1078398, 2386309]]
[[1617891, 2016680, 1841382, 1129442, 2693017, 1755400, 897691, 2112300], [1538952, 2324916, 2044807, 1227134, 2802973, 2290374, 1756977, 2834473]]
[[1771192, 2224129, 1818508, 1215738, 3075512, 2053149, 1818230, 3056334], [1101146, 1842057, 1581610, 698795, 2154583, 1636683, 1209714, 1532227]]
Done!
CPU times: user 22.8 ms, sys: 22.5 ms, total: 45.3 ms
Wall time: 99 ms


## 2. Linear Search

In [105]:
import random
arr = []
for i in range(100):
  arr.append(random.randint(1,45))

In [106]:
arr

[21,
 37,
 24,
 16,
 14,
 22,
 39,
 19,
 14,
 19,
 39,
 17,
 1,
 12,
 13,
 7,
 18,
 32,
 25,
 16,
 5,
 36,
 11,
 43,
 28,
 23,
 41,
 15,
 38,
 35,
 2,
 23,
 24,
 28,
 14,
 12,
 40,
 7,
 35,
 38,
 4,
 1,
 39,
 2,
 1,
 4,
 30,
 20,
 43,
 26,
 22,
 12,
 31,
 15,
 20,
 1,
 9,
 18,
 22,
 12,
 37,
 1,
 7,
 6,
 35,
 30,
 44,
 32,
 5,
 42,
 43,
 16,
 1,
 45,
 18,
 11,
 36,
 22,
 39,
 2,
 30,
 16,
 17,
 12,
 45,
 37,
 16,
 41,
 9,
 11,
 19,
 36,
 18,
 8,
 22,
 8,
 20,
 39,
 17,
 31]

In [107]:
%%time
# Serial
def linear(arr, len, x):
  for i in range(len):
    if(arr[i] == x):
      return i
  return -1

print(linear(arr, len(arr), 45))

73
CPU times: user 0 ns, sys: 578 µs, total: 578 µs
Wall time: 587 µs


In [108]:
r = len(arr)//2
r

50

In [109]:
%%time
# Parallel
def worker1(): 
  print('Worker 1 here!')
  return linear(arr[:r], len(arr[:r]),45)

def worker2(): 
  print('Worker 2 here!')
  return linear(arr[r:], len(arr[r:]),45)

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()


  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  if(worker1()!=-1 and worker2()==-1):
    print(worker1())
  elif(worker1()==-1 and worker2()==-1):
    print(-1)
  elif(worker2()!=-1 and worker1()==-1):
    print(worker2()+50)
  else:
    print(worker1(), worker2()+50)
  print("Done!") 

Worker 1 here!
Worker 2 here!
Worker 1 here!
Worker 1 here!
Worker 2 here!
Worker 2 here!
Worker 1 here!
Worker 2 here!
73
Done!
CPU times: user 6.1 ms, sys: 8.28 ms, total: 14.4 ms
Wall time: 28 ms


In [119]:
def find(arr,idx):
  try:
    return arr.index(idx)
  except ValueError as ve:
    return -1
find(arr,100)

-1

In [120]:
%%time
# Serial - Using Inbuilt
print(find(arr,45))

73
CPU times: user 447 µs, sys: 0 ns, total: 447 µs
Wall time: 455 µs


In [122]:
# Parallel - Using Inbuilt
%%time
def worker1(): 
  return find(arr[:50],45)

def worker2(): 
  return find(arr[50:],45)

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  if(worker1()!=-1 and worker2()==-1):
    print(worker1())
  elif(worker1()==-1 and worker2()==-1):
    print(-1)
  elif(worker2()!=-1 and worker1()==-1):
    print(worker2()+50)
  else:
    print(worker1(), worker2()+50)
  print("Done!") 

73
Done!
CPU times: user 1.38 ms, sys: 8.93 ms, total: 10.3 ms
Wall time: 19.6 ms


In [123]:
arr = []
for i in range(1000):
  arr.append(random.randint(9,199))

In [124]:
%%time
# Serial - Changing Array Size
print(linear(arr, len(arr), 100))

316
CPU times: user 92 µs, sys: 12 µs, total: 104 µs
Wall time: 109 µs


In [129]:
%%time
# Parallel - Changing Array Size
def worker1(): 
  print('Worker 1 here!')
  return linear(arr[:500], len(arr[:500]),100)

def worker2(): 
  print('Worker 2 here!')
  return linear(arr[500:], len(arr[500:]),100)

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  if(worker1()!=-1 and worker2()==-1):
    print(worker1())
  elif(worker1()==-1 and worker2()==-1):
    print(-1)
  elif(worker2()!=-1 and worker1()==-1):
    print(worker2()+500)
  else:
    print(worker1(), worker2()+500)
  print("Done!") 

Worker 1 here!
Worker 2 here!
Worker 1 here!
Worker 2 here!
Worker 1 here!
Worker 2 here!
Worker 1 here!
Worker 1 here!
Worker 2 here!
316 726
Done!
CPU times: user 4.16 ms, sys: 10.2 ms, total: 14.3 ms
Wall time: 30.2 ms


In [131]:
# Parallel - Increasing Threads
%%time
def worker1(): 
  return linear(arr[:250], len(arr[:250]),100)

def worker2(): 
  a = linear(arr[250:500], len(arr[250:500]),100)
  if(a!=-1):
    return a+250
  else:
    return -1
  
def worker3(): 
  a = linear(arr[500:750], len(arr[500:750]),100)
  if(a!=-1):
    return a+500
  else:
    return -1

def worker4(): 
  a = linear(arr[750:], len(arr[750:]),100)
  if(a!=-1):
    return a+750
  else:
    return -1

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)
  p3 = multiprocessing.Process(target=worker3) 
  p4 = multiprocessing.Process(target=worker4)

  # starting processes 
  p1.start() 
  p2.start()
  p3.start() 
  p4.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 
  p3.join() 
  p4.join()

  # both processes finished 
  print(worker1(),worker2(),worker3(),worker4())
  print("Done!") 

-1 316 726 950
Done!
CPU times: user 5.24 ms, sys: 19.3 ms, total: 24.5 ms
Wall time: 31.1 ms


In [132]:
arr = []
for i in range(100):
  arr.append(random.uniform(1,45))
print(arr)

[8.376180544755929, 30.12952920307846, 38.459352249732206, 8.370066596702689, 28.795387108042764, 10.532401261360116, 32.57144276909936, 9.656912723735097, 22.992732534757835, 13.406511699902476, 2.5558992966072878, 20.252843961596774, 1.3238454373275972, 38.977543968987945, 15.066266652974374, 4.797232076616346, 42.87549533947769, 9.728102098055132, 16.528669157950226, 25.92655858194158, 14.678825806041047, 18.158045124829208, 33.35268873055532, 27.578505583022213, 12.835449534591653, 22.707402254223126, 38.62713435574802, 5.059052068292585, 41.83953795955473, 44.296999034449314, 20.61504706971249, 28.15014843962755, 16.043419085374005, 29.539977798311256, 9.697962333162817, 17.114710284284854, 2.8871567274944185, 1.6709671978253633, 13.308857779005118, 31.527127434762637, 9.266613312936487, 20.956173707349226, 8.315418370529287, 16.939159812276056, 9.542261564222237, 28.469162548196948, 15.915252488424697, 27.788620670218297, 25.761609551703536, 33.46348339050046, 39.75091668282507, 

In [133]:
# Serial - Using Float
%%time
linear(arr,len(arr),10.532401261360116)

CPU times: user 8 µs, sys: 1e+03 ns, total: 9 µs
Wall time: 13.6 µs


5

In [134]:
%%time
# Parallel - Using Float
r = len(arr)//2
def worker1(): 
  print('Worker 1 here!')
  return linear(arr[:r], len(arr[:r]),10.532401261360116)

def worker2(): 
  print('Worker 2 here!')
  return linear(arr[r:], len(arr[r:]),10.532401261360116)

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  if(worker1()!=-1 and worker2()==-1):
    print(worker1())
  elif(worker1()==-1 and worker2()==-1):
    print(-1)
  elif(worker2()!=-1 and worker1()==-1):
    print(worker2()+50)
  else:
    print(worker1(), worker2()+50)
  print("Done!") 

Worker 1 here!
Worker 2 here!
Worker 1 here!
Worker 2 here!
Worker 1 here!
5
Done!
CPU times: user 3.57 ms, sys: 10 ms, total: 13.6 ms
Wall time: 23.9 ms


## 3. Array Sum

In [8]:
arr = [i for i in range(1,101)]

In [9]:
%%time
# Serial 
arr = [i for i in range(1,101)]
total = 0
for i in arr:
  total+=i
print(total)

5050
CPU times: user 430 µs, sys: 0 ns, total: 430 µs
Wall time: 435 µs


In [10]:
r = len(arr)//2

In [11]:
%%time
# Parallel
def worker1(): 
   sum1 = 0
   for i in arr[:r]:
       sum1+=i
   print('Worker 1 here!')
   return sum1

def worker2(): 
    sum2 = 0
    for i in arr[r:]:
       sum2+=i
    print('Worker 2 here!')
    return sum2

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print("Final sum: "+str(worker1()+worker2()))
  print("Done!") 

Worker 1 here!
Worker 2 here!
Worker 1 here!
Worker 2 here!
Final sum: 5050
Done!
CPU times: user 3.91 ms, sys: 8.78 ms, total: 12.7 ms
Wall time: 23.7 ms


In [12]:
%%time
# Serial - Using Inbuilt Function
print(sum(arr))

5050
CPU times: user 362 µs, sys: 0 ns, total: 362 µs
Wall time: 763 µs


In [13]:
%%time
# Parallel - Using Inbuilt Function
def worker1(arr): 
   return sum(arr)

def worker2(arr): 
    return sum(arr)

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print("Final sum: "+str(worker1(arr[:50])+worker2(arr[50:])))
  print("Done!") 

Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker1() missing 1 required positional argument: 'arr'
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker2() missing 1 required positional argument: 'arr'


Final sum: 5050
Done!
CPU times: user 10.2 ms, sys: 12.3 ms, total: 22.5 ms
Wall time: 65.8 ms


In [16]:
arr = []
for i in range(1000):
  arr.append(random.randint(9,199))

In [17]:
%%time
# Serial - Changing Array Size
print(sum(arr))

107025
CPU times: user 71 µs, sys: 0 ns, total: 71 µs
Wall time: 75.6 µs


In [18]:
%%time
# Parallel - Changing Array Size
def worker1(arr): 
   return sum(arr)

def worker2(arr): 
    return sum(arr)

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print("Final sum: "+str(worker1(arr[:500])+worker2(arr[500:])))
  print("Done!") 

Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Process Process-8:
TypeError: worker1() missing 1 required positional argument: 'arr'
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker2() missing 1 required positional argument: 'arr'


Final sum: 107025
Done!
CPU times: user 8.13 ms, sys: 15.2 ms, total: 23.3 ms
Wall time: 60.3 ms


In [19]:
# Parallel - Changing No. of Threads
%%time
def worker1(arr): 
   return sum(arr)

def worker2(arr): 
    return sum(arr)

def worker3(arr): 
   return sum(arr)

def worker4(arr): 
    return sum(arr)

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)
  p3 = multiprocessing.Process(target=worker3) 
  p4 = multiprocessing.Process(target=worker4)

  # starting processes 
  p1.start() 
  p2.start()
  p3.start() 
  p4.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 
  p3.join() 
  p4.join() 

  # both processes finished 
  print("Final sum: "+str(worker1(arr[:250])+worker2(arr[250:500])+worker3(arr[500:750])+worker4(arr[750:])))
  print("Done!") 

Process Process-9:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Process Process-10:
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker3() missing 1 required positional argument: 'arr'
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
TypeError: worker1() missing 1 required positional argument: 'arr'
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Process Process-12:
Traceback (most recent call last):
  File "

Final sum: 107025
Done!
CPU times: user 15.7 ms, sys: 29.4 ms, total: 45.1 ms
Wall time: 93 ms


In [22]:
arr = []
for i in range(1000):
  arr.append(random.uniform(9,199))

In [23]:
%%time
# Serial - Using Float Values
print(sum(arr))

104530.72796037045
CPU times: user 336 µs, sys: 0 ns, total: 336 µs
Wall time: 267 µs


In [24]:
%%time
# Parallel - Using Float Values
def worker1(arr): 
   return sum(arr)

def worker2(arr): 
    return sum(arr)

def worker3(arr): 
   return sum(arr)

def worker4(arr): 
    return sum(arr)

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)
  p3 = multiprocessing.Process(target=worker3) 
  p4 = multiprocessing.Process(target=worker4)

  # starting processes 
  p1.start() 
  p2.start()
  p3.start() 
  p4.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 
  p3.join() 
  p4.join() 

  # both processes finished 
  print("Final sum: "+str(worker1(arr[:250])+worker2(arr[250:500])+worker3(arr[500:750])+worker4(arr[750:])))
  print("Done!") 

Process Process-13:
Process Process-14:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Process Process-15:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker1() missing 1 required positional argument: 'arr'
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
TypeError: worker2() missing 1 required positional argument: 'arr'
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker3() missing 1 required positional argument: '

Final sum: 104530.72796037042
Done!
CPU times: user 20.6 ms, sys: 26.8 ms, total: 47.4 ms
Wall time: 104 ms


## 4. Prime Numbers

In [25]:
%%time
# Serial
a = 1
b = 120
for i in range(a, b+1):
   if (i > 1):
       for j in range(2, i):
           if (i % j) == 0:
               break
       else:
           print(i)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
CPU times: user 1.95 ms, sys: 0 ns, total: 1.95 ms
Wall time: 1.41 ms


In [26]:
%%time
# Parallel
def prime(a, b):
  for i in range(a, b+1):
   if (i > 1):
       for j in range(2, i):
           if (i % j) == 0:
               break
       else:
           print(i)

def worker1(): 
  prime(1,30)  

def worker2(): 
  prime(31,60)

def worker3(): 
  prime(61,90)

def worker4(): 
  prime(91,120)

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2) 
  p3 = multiprocessing.Process(target=worker3) 
  p4 = multiprocessing.Process(target=worker4) 

  # starting processes 
  p1.start() 
  p2.start() 
  p3.start() 
  p4.start()


  # wait until processes are finished 
  p1.join() 
  p2.join() 
  p3.join() 
  p4.join() 

  # both processes finished 
  print("Done!") 


2
31
37
41
43
47
53
3
59
5
7
61
11
67
13
17
97
71
101
73
79
19
83
23
89
103
29
107
109
113
Done!
CPU times: user 22.2 ms, sys: 39.7 ms, total: 61.9 ms
Wall time: 113 ms


In [28]:
%%time
# Parallel - Changing No. of Threads

def worker1(): 
  prime(1,60)  

def worker2(): 
  prime(61,120)

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2) 

  # starting processes 
  p1.start() 
  p2.start() 

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print("Done!") 

2
3
61
5
67
7
11
13
71
17
73
79
19
23
29
83
89
31
97
101
103
37
41
43
107
47
53
109
113
59
Done!
CPU times: user 20.6 ms, sys: 18.8 ms, total: 39.3 ms
Wall time: 101 ms


In [29]:
%%time
# Serial - Changing N Size
prime(1,1000)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997
CPU times: user 17.5 ms, sys: 4.06 ms, total: 21.6 ms
Wall time: 20.3 ms


In [30]:
%%time
# Parallel - Changing N Size
def worker1(): 
  prime(1,500)  

def worker2(): 
  prime(501,1000)

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2) 

  # starting processes 
  p1.start() 
  p2.start() 

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print("Done!") 

2
3
5
503
509
521
523
541
7
11
547
13
557
17
563
19
23
569
571
29
577
31
37
41
587
43
47
53
59
593
61
67
71
73
599
79
83
601
89
607
613
617
619
631
97
641
101
103
107
109
113
643
127
647
653
659
661
673
131
677
683
691
701
709
137
719
727
139
149
733
151
739
157
743
751
163
757
761
167
769
173
773
179
181
787
797
191
809
811
193
821
197
823
199
827
829
211
839
223
227
853
857
229
859
863
233
877
239
241
881
251
883
257
887
263
907
269
911
919
271
277
929
937
281
283
293
307
941
947
311
953
313
967
971
317
331
977
337
983
347
349
991
353
359
367
997
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
Done!
CPU times: user 110 ms, sys: 47.8 ms, total: 158 ms
Wall time: 548 ms
