In [1]:
import multiprocessing
import os
import time
import numpy
import itertools 

In [77]:
multiprocessing.cpu_count()

2

### 1. Prime in a Power Set

In [2]:
def isprime(num):
  if(num>1):
   for i in range(2,num):
       if(num%i)==0:
           return False
   else:
           return True
  else:
      return False

In [3]:
isprime(31)

True

In [79]:
def findsubsets(s): 
    lst = []
    for i in range(1, len(s)+1):
      lst.append(list(itertools.combinations(s, i)))
    return lst

def printprime(s):
  lst = findsubsets(s)
  primes = []
  for i in lst:
    for j in i:
      if(isprime(sum(list(j)))):
        primes.append(j)
  return primes

In [80]:
arr = []
for i in range(1,19):
  arr.append(i)
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [81]:
%%time
print(printprime(arr))

[(2,), (3,), (5,), (7,), (11,), (13,), (17,), (1, 2), (1, 4), (1, 6), (1, 10), (1, 12), (1, 16), (1, 18), (2, 3), (2, 5), (2, 9), (2, 11), (2, 15), (2, 17), (3, 4), (3, 8), (3, 10), (3, 14), (3, 16), (4, 7), (4, 9), (4, 13), (4, 15), (5, 6), (5, 8), (5, 12), (5, 14), (5, 18), (6, 7), (6, 11), (6, 13), (6, 17), (7, 10), (7, 12), (7, 16), (8, 9), (8, 11), (8, 15), (9, 10), (9, 14), (10, 13), (11, 12), (11, 18), (12, 17), (13, 16), (13, 18), (14, 15), (14, 17), (15, 16), (1, 2, 4), (1, 2, 8), (1, 2, 10), (1, 2, 14), (1, 2, 16), (1, 3, 7), (1, 3, 9), (1, 3, 13), (1, 3, 15), (1, 4, 6), (1, 4, 8), (1, 4, 12), (1, 4, 14), (1, 4, 18), (1, 5, 7), (1, 5, 11), (1, 5, 13), (1, 5, 17), (1, 6, 10), (1, 6, 12), (1, 6, 16), (1, 7, 9), (1, 7, 11), (1, 7, 15), (1, 8, 10), (1, 8, 14), (1, 9, 13), (1, 10, 12), (1, 10, 18), (1, 11, 17), (1, 12, 16), (1, 12, 18), (1, 13, 15), (1, 13, 17), (1, 14, 16), (2, 3, 6), (2, 3, 8), (2, 3, 12), (2, 3, 14), (2, 3, 18), (2, 4, 5), (2, 4, 7), (2, 4, 11), (2, 4, 13), (2,

In [82]:
%%time
def worker1(arr): 
  return printprime(arr)


def worker2(arr): 
  return printprime(arr)

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  print(worker1(arr[:9]))
  print(worker2(arr[9:]))
  print("Done!") 

Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Process Process-8:
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
TypeError: worker1() missing 1 required positional argument: 'arr'
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker2() missing 1 required positional argument: 'arr'


[(2,), (3,), (5,), (7,), (1, 2), (1, 4), (1, 6), (2, 3), (2, 5), (2, 9), (3, 4), (3, 8), (4, 7), (4, 9), (5, 6), (5, 8), (6, 7), (8, 9), (1, 2, 4), (1, 2, 8), (1, 3, 7), (1, 3, 9), (1, 4, 6), (1, 4, 8), (1, 5, 7), (1, 7, 9), (2, 3, 6), (2, 3, 8), (2, 4, 5), (2, 4, 7), (2, 5, 6), (2, 6, 9), (2, 7, 8), (2, 8, 9), (3, 4, 6), (3, 5, 9), (3, 6, 8), (3, 7, 9), (4, 5, 8), (4, 6, 7), (4, 6, 9), (4, 7, 8), (5, 6, 8), (6, 8, 9), (1, 2, 3, 5), (1, 2, 3, 7), (1, 2, 4, 6), (1, 2, 5, 9), (1, 2, 6, 8), (1, 2, 7, 9), (1, 3, 4, 5), (1, 3, 4, 9), (1, 3, 5, 8), (1, 3, 6, 7), (1, 3, 6, 9), (1, 3, 7, 8), (1, 4, 5, 7), (1, 4, 5, 9), (1, 4, 6, 8), (1, 5, 6, 7), (1, 5, 8, 9), (1, 6, 7, 9), (2, 3, 4, 8), (2, 3, 5, 7), (2, 3, 5, 9), (2, 3, 6, 8), (2, 4, 5, 6), (2, 4, 5, 8), (2, 4, 6, 7), (2, 4, 8, 9), (2, 5, 7, 9), (2, 6, 7, 8), (3, 4, 5, 7), (3, 4, 7, 9), (3, 5, 6, 9), (3, 5, 7, 8), (4, 5, 6, 8), (5, 7, 8, 9), (1, 2, 3, 4, 7), (1, 2, 3, 4, 9), (1, 2, 3, 5, 6), (1, 2, 3, 5, 8), (1, 2, 3, 6, 7), (1, 2, 3, 8, 9),

### 2. Word Search in English Dictionary

In [67]:
!wget https://raw.githubusercontent.com/dwyl/english-words/master/words.txt

--2021-01-20 05:07:38--  https://raw.githubusercontent.com/dwyl/english-words/master/words.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4862992 (4.6M) [text/plain]
Saving to: ‘words.txt’

words.txt           100%[===================>]   4.64M  29.4MB/s    in 0.2s    

2021-01-20 05:07:38 (29.4 MB/s) - ‘words.txt’ saved [4862992/4862992]



In [83]:
def isPalindrome(s):
    return s == s[::-1]

In [93]:
f = open('words.txt', 'r') 
Lines = f.readlines() 
palin = []
for line in Lines: 
    line = line.strip()
    if(isPalindrome(line)):
      palin.append(line)

In [91]:
%%time
print(palin)

['2', 'a', 'AA', 'AAA', 'AAAA', 'AAAAAA', 'ABA', 'acca', 'ADA', 'addda', 'AEA', 'AFA', 'affa', 'aga', 'AHA', 'AIA', 'AJA', 'AKA', 'ALA', 'alula', 'AMA', 'ana', 'AOA', 'APA', 'ARA', 'ASA', 'ATA', 'AUA', 'awa', 'B', 'B/B', 'BB', 'BBB', 'boob', 'C', 'CAC', 'CAMAC', 'CBC', 'CC', 'CCC', 'CDC', 'CEC', 'CFC', 'CIC', 'cyc', 'civic', 'CMC', 'CNC', 'COC', 'CPC', 'CRC', 'CSC', 'CTC', 'CTTC', 'CWC', 'D', 'DAD', 'DCD', 'DD', 'DDD', 'deed', 'deedeed', 'degged', 'deified', 'deked', 'deled', 'denned', 'dewed', 'DFD', 'DID', 'divid', 'DMD', 'DOD', 'DRD', 'DSD', 'dtd', 'E', 'ecce', 'ECE', 'ee', 'EEE', 'eye', 'eke', 'ELLE', 'eme', 'ene', 'EOE', 'ERE', 'ese', 'esse', 'ette', 'F', 'FF', 'FSF', 'G', 'GBG', 'GG', 'gig', 'goog', 'H', 'hagigah', 'hah', 'halalah', 'hallah', 'heh', 'HH', 'HIH', 'HRH', 'HSH', 'huh', 'i', 'y', '-i-', 'yay', 'yaray', 'ICI', 'IDI', 'ihi', 'ii', 'YY', 'iii', 'imi', 'immi', 'yoy', 'IPI', 'ISI', 'ISSI', 'J', 'JJ', 'K', 'kaiak', 'kayak', 'kakkak', 'keek', 'kelek', 'kinnikinnik', 'KKK', 

In [87]:
len(Lines)//2

233275

In [95]:
%%time
def worker1(Lines): 
  palin = []
  for line in Lines: 
    line = line.strip()
    if(isPalindrome(line)):
      palin.append(line)
  return palin


def worker2(Lines): 
  palin = []
  for line in Lines: 
    line = line.strip()
    if(isPalindrome(line)):
      palin.append(line)
  return palin

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  print(worker1(Lines[:233275]))
  print(worker2(Lines[233275:]))
  print("Done!") 

Process Process-17:
Process Process-18:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker1() missing 1 required positional argument: 'Lines'
TypeError: worker2() missing 1 required positional argument: 'Lines'


['2', 'a', 'AA', 'AAA', 'AAAA', 'AAAAAA', 'ABA', 'acca', 'ADA', 'addda', 'AEA', 'AFA', 'affa', 'aga', 'AHA', 'AIA', 'AJA', 'AKA', 'ALA', 'alula', 'AMA', 'ana', 'AOA', 'APA', 'ARA', 'ASA', 'ATA', 'AUA', 'awa', 'B', 'B/B', 'BB', 'BBB', 'boob', 'C', 'CAC', 'CAMAC', 'CBC', 'CC', 'CCC', 'CDC', 'CEC', 'CFC', 'CIC', 'cyc', 'civic', 'CMC', 'CNC', 'COC', 'CPC', 'CRC', 'CSC', 'CTC', 'CTTC', 'CWC', 'D', 'DAD', 'DCD', 'DD', 'DDD', 'deed', 'deedeed', 'degged', 'deified', 'deked', 'deled', 'denned', 'dewed', 'DFD', 'DID', 'divid', 'DMD', 'DOD', 'DRD', 'DSD', 'dtd', 'E', 'ecce', 'ECE', 'ee', 'EEE', 'eye', 'eke', 'ELLE', 'eme', 'ene', 'EOE', 'ERE', 'ese', 'esse', 'ette', 'F', 'FF', 'FSF', 'G', 'GBG', 'GG', 'gig', 'goog', 'H', 'hagigah', 'hah', 'halalah', 'hallah', 'heh', 'HH', 'HIH', 'HRH', 'HSH', 'huh', 'i', 'y', '-i-', 'yay', 'yaray', 'ICI', 'IDI', 'ihi', 'ii', 'YY', 'iii', 'imi', 'immi', 'yoy', 'IPI', 'ISI', 'ISSI', 'J', 'JJ', 'K', 'kaiak', 'kayak', 'kakkak', 'keek', 'kelek', 'kinnikinnik', 'KKK', 

### 3. Image Convolution:

In [96]:
!wget https://ocdn.eu/images/pulscms/NGY7MDA_/f8d05506e9250de59fa645f0fb7020e4.jpg

--2021-01-20 05:24:38--  https://ocdn.eu/images/pulscms/NGY7MDA_/f8d05506e9250de59fa645f0fb7020e4.jpg
Resolving ocdn.eu (ocdn.eu)... 213.180.141.132, 213.180.141.128
Connecting to ocdn.eu (ocdn.eu)|213.180.141.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2271166 (2.2M) [image/jpeg]
Saving to: ‘f8d05506e9250de59fa645f0fb7020e4.jpg’

f8d05506e9250de59fa 100%[===================>]   2.17M  2.21MB/s    in 1.0s    

2021-01-20 05:24:40 (2.21 MB/s) - ‘f8d05506e9250de59fa645f0fb7020e4.jpg’ saved [2271166/2271166]



In [97]:
import cv2
image = cv2.imread("f8d05506e9250de59fa645f0fb7020e4.jpg")

In [99]:
image

array([[[ 54,  34,  17],
        [ 54,  35,  22],
        [ 56,  34,  28],
        ...,
        [ 78, 114, 130],
        [ 79, 115, 131],
        [ 79, 115, 131]],

       [[ 51,  34,  15],
        [ 53,  35,  18],
        [ 54,  35,  27],
        ...,
        [ 76, 112, 130],
        [ 77, 113, 129],
        [ 78, 114, 132]],

       [[ 49,  38,  11],
        [ 49,  36,  14],
        [ 50,  37,  21],
        ...,
        [ 71, 108, 128],
        [ 73, 111, 129],
        [ 75, 112, 132]],

       ...,

       [[  7,   2,   3],
        [  7,   2,   3],
        [  8,   2,   3],
        ...,
        [ 17,  12,  14],
        [ 14,   9,  10],
        [ 15,  10,  11]],

       [[  7,   2,   3],
        [  7,   2,   3],
        [  8,   2,   3],
        ...,
        [ 20,  15,  17],
        [ 15,  10,  11],
        [ 12,  10,  10]],

       [[  8,   3,   4],
        [  8,   3,   4],
        [  8,   2,   3],
        ...,
        [ 20,  15,  17],
        [ 16,  11,  12],
        [ 12,  10,  10]]

In [105]:
import numpy as np

In [106]:
kernel = [[0, 1, 0],
	[1, -4, 1],
	[0, 1, 0]]
kernel3d = []
for i in range(3):
  kernel3d.append(kernel)

kernel3d = np.array(kernel3d)

In [108]:
import scipy.ndimage

In [111]:
image.shape

(3000, 2405, 3)

In [113]:
kernel3d.shape

(3, 3, 3)

In [121]:
%%time
print(scipy.ndimage.convolve(image, kernel3d))

[[[201   7  66]
  [203   8  51]
  [194  55  24]
  ...
  [106 196 200]
  [106 194 210]
  [107 197 203]]

 [[210 241  74]
  [208 254  63]
  [208  37  37]
  ...
  [110 204 197]
  [109 193 211]
  [106 199 196]]

 [[221 210  79]
  [223 234  85]
  [227  14  53]
  ...
  [113 215 199]
  [118 191 209]
  [102 200 189]]

 ...

 [[242  19 254]
  [243  17 252]
  [229  18 250]
  ...
  [237  17 241]
  [250  30  11]
  [244  11 252]]

 [[241  18 253]
  [243  17 252]
  [230  19 251]
  ...
  [232  12 237]
  [247  30  10]
  [253  10   1]]

 [[241  18 253]
  [242  16 251]
  [231  20 252]
  ...
  [229   9 235]
  [243  29   8]
  [  5   8   5]]]
CPU times: user 1.07 s, sys: 14.7 ms, total: 1.08 s
Wall time: 1.09 s


In [124]:
%%time
def worker1(image): 
  return scipy.ndimage.convolve(image, kernel3d)

def worker2(image): 
  return scipy.ndimage.convolve(image, kernel3d)

if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  print(worker1(image[:1500,:1200,:]))
  print(worker2(image[1500:,1200:,:]))
  print("Done!") 

Process Process-19:
Traceback (most recent call last):
Process Process-20:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker2() missing 1 required positional argument: 'image'
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker1() missing 1 required positional argument: 'image'


[[[201   7  66]
  [203   8  51]
  [194  55  24]
  ...
  [  4 248 254]
  [  9 253   3]
  [  6 250   0]]

 [[210 241  74]
  [208 254  63]
  [208  37  37]
  ...
  [  6 250   0]
  [  7 251   1]
  [  7 251   1]]

 [[221 210  79]
  [223 234  85]
  [227  14  53]
  ...
  [  7 251   1]
  [  6 250   0]
  [  7 251   1]]

 ...

 [[253  92 210]
  [241  59 197]
  [232  60 185]
  ...
  [ 91  71  97]
  [100  67  98]
  [ 93  69  91]]

 [[252  73 225]
  [247  46 211]
  [237  41 203]
  ...
  [ 89  73  94]
  [ 97  68  94]
  [ 95  75  92]]

 [[250  61 234]
  [252  39 218]
  [239  30 215]
  ...
  [ 87  75  91]
  [ 96  72  91]
  [ 96  75  94]]]
[[[ 90  60  92]
  [ 94  68  97]
  [ 99  70 103]
  ...
  [ 97 213 209]
  [ 90 216 181]
  [ 84 231 197]]

 [[ 89  57  90]
  [ 98  69  99]
  [ 98  70 105]
  ...
  [ 96 208 211]
  [ 93 208 187]
  [ 85 227 201]]

 [[ 88  59  86]
  [101  68 101]
  [ 97  70 107]
  ...
  [ 96 203 211]
  [ 97 201 196]
  [ 87 219 207]]

 ...

 [[213 124 255]
  [ 58 235 157]
  [ 53 223 151]
  ..