## HPC Lab-6
Name: Tanvi Penumudy

Enroll No: E18CSE187

In [16]:
import multiprocessing 
import os 
import time
import numpy as np

I. Serial Implementation


In [77]:
import random
X = [random.choices(range(9,999), k=4) for _ in range(4)]
Y = [random.choices(range(9,999), k=4) for _ in range(4)]
result = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]

In [78]:
print(X)
print(Y)
print(result)

[[882, 741, 572, 992], [519, 305, 962, 425], [199, 395, 599, 881], [399, 426, 772, 371]]
[[70, 891, 226, 183], [884, 649, 690, 930], [528, 953, 937, 247], [729, 730, 622, 406]]
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [79]:
%%time
for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
print(result)

[[1741968, 2536047, 1863610, 1394572], [1123711, 1887410, 1493488, 788791], [1321631, 1647641, 1426769, 909406], [1082589, 1638529, 1338240, 810507]]
CPU times: user 1.16 ms, sys: 16 µs, total: 1.18 ms
Wall time: 1.24 ms


In [80]:
# Changing N Value
U = [random.choices(range(9,999), k=8) for _ in range(8)]
V = [random.choices(range(9,999), k=8) for _ in range(8)]
def zeros(rows,cols):
  return [([0]*cols) for i in range(rows)]
r = zeros(8,8)

In [81]:
%%time
for i in range(len(U)):
   for j in range(len(V[0])):
       for k in range(len(V)):
           r[i][j] += U[i][k] * V[k][j]
print(r)

[[1785161, 2066644, 2052930, 1615890, 1881700, 1568936, 846661, 1048269], [2754460, 2520839, 2577981, 2247542, 2719076, 1605787, 1472405, 1560552], [2023084, 1826475, 1796767, 1137473, 2115736, 864259, 1230269, 1603023], [1916034, 1675327, 1907385, 1665524, 1823832, 1187624, 1225676, 1067248], [2451892, 1658709, 1953031, 2324864, 2030310, 1249589, 1438451, 1114459], [3528284, 3305970, 3163650, 2728300, 3351610, 2315535, 1811483, 2434469], [3185363, 3127996, 2867473, 2654045, 3161196, 2142059, 1219570, 1842523], [2280625, 2120251, 2034148, 2069679, 2145635, 1585113, 1334458, 1693992]]
CPU times: user 443 µs, sys: 0 ns, total: 443 µs
Wall time: 453 µs


In [82]:
# Changing Data Type
K = np.random.uniform(9,999,[4,4])
L = np.random.uniform(9,999,[4,4])
res = np.zeros((4,4))
K = K.tolist()
L = L.tolist()

In [83]:
%%time
for i in range(len(K)):
   for j in range(len(L[0])):
       for k in range(len(L)):
           res[i][j] += K[i][k] * L[k][j]
print(res)

[[ 818679.58652817 1234585.38164184  973918.98366409  868929.70269772]
 [ 828679.24059353 1326752.72918571 1142772.50337486  967767.49205869]
 [1252739.47616991 1503658.07291444  885776.79615036  910204.92619964]
 [1293781.93738312 1620874.2669811  1269688.05380174 1137132.26054797]]
CPU times: user 902 µs, sys: 0 ns, total: 902 µs
Wall time: 815 µs


II. Data Parallel Implementation 

In [84]:
%%time
def worker1(X, Y, result): 
  for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
  return result

def worker2(X, Y, result):
  for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
  return result
  
if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print(worker1(X[:2],Y,[[0,0,0,0],[0,0,0,0]]))
  print(worker2(X[2:],Y,[[0,0,0,0],[0,0,0,0]]))
  print("Done!")

Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Process Process-8:
TypeError: worker1() missing 3 required positional arguments: 'X', 'Y', and 'result'
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker2() missing 3 required positional arguments: 'X', 'Y', and 'result'


[[1741968, 2536047, 1863610, 1394572], [1123711, 1887410, 1493488, 788791]]
[[1321631, 1647641, 1426769, 909406], [1082589, 1638529, 1338240, 810507]]
Done!
CPU times: user 9.62 ms, sys: 19 ms, total: 28.7 ms
Wall time: 68.2 ms


In [85]:
# Changing N Value
%%time
def worker1(X, Y, result): 
  for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
  return result

def worker2(X, Y, result):
  for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
  return result
  
if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print(worker1(U[:4],V,zeros(4,8)))
  print(worker2(U[4:],V,zeros(4,8)))
  print("Done!")

Process Process-9:
Traceback (most recent call last):
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker1() missing 3 required positional arguments: 'X', 'Y', and 'result'
TypeError: worker2() missing 3 required positional arguments: 'X', 'Y', and 'result'


[[1785161, 2066644, 2052930, 1615890, 1881700, 1568936, 846661, 1048269], [2754460, 2520839, 2577981, 2247542, 2719076, 1605787, 1472405, 1560552], [2023084, 1826475, 1796767, 1137473, 2115736, 864259, 1230269, 1603023], [1916034, 1675327, 1907385, 1665524, 1823832, 1187624, 1225676, 1067248]]
[[2451892, 1658709, 1953031, 2324864, 2030310, 1249589, 1438451, 1114459], [3528284, 3305970, 3163650, 2728300, 3351610, 2315535, 1811483, 2434469], [3185363, 3127996, 2867473, 2654045, 3161196, 2142059, 1219570, 1842523], [2280625, 2120251, 2034148, 2069679, 2145635, 1585113, 1334458, 1693992]]
Done!
CPU times: user 9.17 ms, sys: 16.8 ms, total: 26 ms
Wall time: 63.3 ms


In [87]:
# Changing Data Type
def worker1(X, Y, result): 
  for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
  return result

def worker2(X, Y, result):
  for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
  return result
  
if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print(worker1(K[:2],L,np.zeros((2,4))))
  print(worker2(K[2:],L,np.zeros((2,4))))
  print("Done!")

Process Process-13:
Process Process-14:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker2() missing 3 required positional arguments: 'X', 'Y', and 'result'
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker1() missing 3 required positional arguments: 'X', 'Y', and 'result'


[[ 818679.58652817 1234585.38164184  973918.98366409  868929.70269772]
 [ 828679.24059353 1326752.72918571 1142772.50337486  967767.49205869]]
[[1252739.47616991 1503658.07291444  885776.79615036  910204.92619964]
 [1293781.93738312 1620874.2669811  1269688.05380174 1137132.26054797]]
Done!


III. Numpy

In [88]:
A = np.array(X)
B = np.array(Y)

In [89]:
%%time
print(np.dot(A,B))

[[1741968 2536047 1863610 1394572]
 [1123711 1887410 1493488  788791]
 [1321631 1647641 1426769  909406]
 [1082589 1638529 1338240  810507]]
CPU times: user 273 µs, sys: 27 µs, total: 300 µs
Wall time: 305 µs


In [90]:
# Changing N Value
C = np.array(U)
D = np.array(V)

In [91]:
%%time
print(np.dot(C,D))

[[1785161 2066644 2052930 1615890 1881700 1568936  846661 1048269]
 [2754460 2520839 2577981 2247542 2719076 1605787 1472405 1560552]
 [2023084 1826475 1796767 1137473 2115736  864259 1230269 1603023]
 [1916034 1675327 1907385 1665524 1823832 1187624 1225676 1067248]
 [2451892 1658709 1953031 2324864 2030310 1249589 1438451 1114459]
 [3528284 3305970 3163650 2728300 3351610 2315535 1811483 2434469]
 [3185363 3127996 2867473 2654045 3161196 2142059 1219570 1842523]
 [2280625 2120251 2034148 2069679 2145635 1585113 1334458 1693992]]
CPU times: user 1.17 ms, sys: 16 µs, total: 1.19 ms
Wall time: 944 µs


In [92]:
# Changing Data Type
E = np.array(K)
F = np.array(L)

In [93]:
%%time
print(np.dot(E,F))

[[ 818679.58652817 1234585.38164184  973918.98366409  868929.70269772]
 [ 828679.24059353 1326752.72918571 1142772.50337486  967767.49205869]
 [1252739.47616991 1503658.07291444  885776.79615036  910204.92619964]
 [1293781.93738312 1620874.2669811  1269688.05380174 1137132.26054797]]
CPU times: user 1.28 ms, sys: 22 µs, total: 1.3 ms
Wall time: 1.17 ms


IV. Scipy


In [94]:
from scipy import linalg

In [95]:
A = np.array(X)
B = np.array(Y)

In [96]:
%%time
print(A.dot(B))

[[1741968 2536047 1863610 1394572]
 [1123711 1887410 1493488  788791]
 [1321631 1647641 1426769  909406]
 [1082589 1638529 1338240  810507]]
CPU times: user 1.01 ms, sys: 100 µs, total: 1.11 ms
Wall time: 1 ms


In [97]:
# Changing N Value
%%time
print(C.dot(D))

[[1785161 2066644 2052930 1615890 1881700 1568936  846661 1048269]
 [2754460 2520839 2577981 2247542 2719076 1605787 1472405 1560552]
 [2023084 1826475 1796767 1137473 2115736  864259 1230269 1603023]
 [1916034 1675327 1907385 1665524 1823832 1187624 1225676 1067248]
 [2451892 1658709 1953031 2324864 2030310 1249589 1438451 1114459]
 [3528284 3305970 3163650 2728300 3351610 2315535 1811483 2434469]
 [3185363 3127996 2867473 2654045 3161196 2142059 1219570 1842523]
 [2280625 2120251 2034148 2069679 2145635 1585113 1334458 1693992]]
CPU times: user 1.02 ms, sys: 2 µs, total: 1.02 ms
Wall time: 1.04 ms


In [98]:
# Changing Data Type
%%time
print(E.dot(F))

[[ 818679.58652817 1234585.38164184  973918.98366409  868929.70269772]
 [ 828679.24059353 1326752.72918571 1142772.50337486  967767.49205869]
 [1252739.47616991 1503658.07291444  885776.79615036  910204.92619964]
 [1293781.93738312 1620874.2669811  1269688.05380174 1137132.26054797]]
CPU times: user 1.62 ms, sys: 61 µs, total: 1.68 ms
Wall time: 1.74 ms


V. Pandas

In [99]:
import pandas as pd

In [100]:
A = pd.DataFrame(X)
B = pd.DataFrame(Y)

In [101]:
%%time
print(A.dot(B))

         0        1        2        3
0  1741968  2536047  1863610  1394572
1  1123711  1887410  1493488   788791
2  1321631  1647641  1426769   909406
3  1082589  1638529  1338240   810507
CPU times: user 9.42 ms, sys: 5.89 ms, total: 15.3 ms
Wall time: 20.8 ms


In [102]:
# Changing N Value
C = pd.DataFrame(U)
D = pd.DataFrame(V)

In [103]:
%%time
print(C.dot(D))

         0        1        2        3        4        5        6        7
0  1785161  2066644  2052930  1615890  1881700  1568936   846661  1048269
1  2754460  2520839  2577981  2247542  2719076  1605787  1472405  1560552
2  2023084  1826475  1796767  1137473  2115736   864259  1230269  1603023
3  1916034  1675327  1907385  1665524  1823832  1187624  1225676  1067248
4  2451892  1658709  1953031  2324864  2030310  1249589  1438451  1114459
5  3528284  3305970  3163650  2728300  3351610  2315535  1811483  2434469
6  3185363  3127996  2867473  2654045  3161196  2142059  1219570  1842523
7  2280625  2120251  2034148  2069679  2145635  1585113  1334458  1693992
CPU times: user 11.8 ms, sys: 12 µs, total: 11.8 ms
Wall time: 14.1 ms


In [105]:
# Changing Data Frame
E = pd.DataFrame(K)
F = pd.DataFrame(L)

In [106]:
%%time
print(E.dot(F))

              0             1             2             3
0  8.186796e+05  1.234585e+06  9.739190e+05  8.689297e+05
1  8.286792e+05  1.326753e+06  1.142773e+06  9.677675e+05
2  1.252739e+06  1.503658e+06  8.857768e+05  9.102049e+05
3  1.293782e+06  1.620874e+06  1.269688e+06  1.137132e+06
CPU times: user 10.1 ms, sys: 0 ns, total: 10.1 ms
Wall time: 10.9 ms


VI. Sympy

In [107]:
from sympy import *

In [108]:
A = Matrix(X)
B = Matrix(Y)

In [109]:
A

Matrix([
[882, 741, 572, 992],
[519, 305, 962, 425],
[199, 395, 599, 881],
[399, 426, 772, 371]])

In [110]:
B

Matrix([
[ 70, 891, 226, 183],
[884, 649, 690, 930],
[528, 953, 937, 247],
[729, 730, 622, 406]])

In [111]:
%%time
print(A*B)

Matrix([[1741968, 2536047, 1863610, 1394572], [1123711, 1887410, 1493488, 788791], [1321631, 1647641, 1426769, 909406], [1082589, 1638529, 1338240, 810507]])
CPU times: user 4.23 ms, sys: 987 µs, total: 5.22 ms
Wall time: 5.25 ms


In [112]:
# Changing N Value
C = Matrix(U)
D = Matrix(V)

In [113]:
%%time
print(C*D)

Matrix([[1785161, 2066644, 2052930, 1615890, 1881700, 1568936, 846661, 1048269], [2754460, 2520839, 2577981, 2247542, 2719076, 1605787, 1472405, 1560552], [2023084, 1826475, 1796767, 1137473, 2115736, 864259, 1230269, 1603023], [1916034, 1675327, 1907385, 1665524, 1823832, 1187624, 1225676, 1067248], [2451892, 1658709, 1953031, 2324864, 2030310, 1249589, 1438451, 1114459], [3528284, 3305970, 3163650, 2728300, 3351610, 2315535, 1811483, 2434469], [3185363, 3127996, 2867473, 2654045, 3161196, 2142059, 1219570, 1842523], [2280625, 2120251, 2034148, 2069679, 2145635, 1585113, 1334458, 1693992]])
CPU times: user 8.41 ms, sys: 0 ns, total: 8.41 ms
Wall time: 13.8 ms


In [114]:
# Changing Data Type
E = Matrix(K)
F = Matrix(L)

In [115]:
%%time
print(E*F)

Matrix([[818679.586528175, 1234585.38164184, 973918.983664087, 868929.702697720], [828679.240593528, 1326752.72918571, 1142772.50337486, 967767.492058695], [1252739.47616991, 1503658.07291444, 885776.796150356, 910204.926199641], [1293781.93738312, 1620874.26698110, 1269688.05380174, 1137132.26054797]])
CPU times: user 7.95 ms, sys: 0 ns, total: 7.95 ms
Wall time: 7.98 ms


VII. Numba

In [116]:
import numba
from numba import jit

In [117]:
@jit('void(int64[:,:],int64[:,:],int64[:,:])')
def numba_mul(matrix1,matrix2,rmatrix):
  for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
      for k in range(len(matrix2)):
        rmatrix[i][j] += matrix1[i][k] * matrix2[k][j]

In [118]:
matrix1 = np.array(X)
matrix2 = np.array(Y)
rmatrix = np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]])

In [119]:
%%time
numba_mul(matrix1,matrix2,rmatrix)
for r in rmatrix:
  print(r)

[1741968 2536047 1863610 1394572]
[1123711 1887410 1493488  788791]
[1321631 1647641 1426769  909406]
[1082589 1638529 1338240  810507]
CPU times: user 2.23 ms, sys: 827 µs, total: 3.06 ms
Wall time: 4.46 ms


In [120]:
# Changing N Value
matrix1 = np.array(U)
matrix2 = np.array(V)
rmatrix = np.array([[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0]])

In [121]:
%%time
numba_mul(matrix1,matrix2,rmatrix)
for r in rmatrix:
  print(r)

[1785161 2066644 2052930 1615890 1881700 1568936  846661 1048269]
[2754460 2520839 2577981 2247542 2719076 1605787 1472405 1560552]
[2023084 1826475 1796767 1137473 2115736  864259 1230269 1603023]
[1916034 1675327 1907385 1665524 1823832 1187624 1225676 1067248]
[2451892 1658709 1953031 2324864 2030310 1249589 1438451 1114459]
[3528284 3305970 3163650 2728300 3351610 2315535 1811483 2434469]
[3185363 3127996 2867473 2654045 3161196 2142059 1219570 1842523]
[2280625 2120251 2034148 2069679 2145635 1585113 1334458 1693992]
CPU times: user 2.69 ms, sys: 988 µs, total: 3.68 ms
Wall time: 6.59 ms


In [122]:
# Changing Data Type
@jit('void(float64[:,:],float64[:,:],float64[:,:])')
def numba_mul(matrix1,matrix2,rmatrix):
  for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
      for k in range(len(matrix2)):
        rmatrix[i][j] += matrix1[i][k] * matrix2[k][j]

matrix1 = np.array(K)
matrix2 = np.array(L)
rmatrix = np.zeros((4,4))

In [123]:
%%time
numba_mul(matrix1,matrix2,rmatrix)
for r in rmatrix:
  print(r)

[ 818679.58652817 1234585.38164184  973918.98366409  868929.70269772]
[ 828679.24059353 1326752.72918571 1142772.50337486  967767.49205869]
[1252739.47616991 1503658.07291444  885776.79615036  910204.92619964]
[1293781.93738312 1620874.2669811  1269688.05380174 1137132.26054797]
CPU times: user 1.48 ms, sys: 1.05 ms, total: 2.53 ms
Wall time: 2.24 ms


VIII. Linalg

In [124]:
!pip install linalg

  Created wheel for linalg: filename=linalg-1.0.4-cp36-none-any.whl size=6294 sha256=21d039c6a185c3cad2dad25dad1c7d9fc7849f83f0bc3a53d6058196d40298a9
  Stored in directory: /root/.cache/pip/wheels/a6/09/2b/ed39c10f756adfcf310484fda9ff8ca0f647fc08fb2171a76b
Successfully built linalg


In [125]:
import linalg

In [126]:
A = linalg.Matrix(X) 
B = linalg.Matrix(Y) 

In [127]:
%%time
print(A@B)

|17419 25360 18636 13945 |
|11237 18874 14934 78879 |
|13216 16476 14267 90940 |
|10825 16385 13382 81050 |

CPU times: user 741 µs, sys: 0 ns, total: 741 µs
Wall time: 755 µs


In [128]:
# Changing N Value
C = linalg.Matrix(U) 
D = linalg.Matrix(V) 

In [129]:
%%time
print(C@D)

|17851 20666 20529 16158 18817 15689 84666 10482 |
|27544 25208 25779 22475 27190 16057 14724 15605 |
|20230 18264 17967 11374 21157 86425 12302 16030 |
|19160 16753 19073 16655 18238 11876 12256 10672 |
|24518 16587 19530 23248 20303 12495 14384 11144 |
|35282 33059 31636 27283 33516 23155 18114 24344 |
|31853 31279 28674 26540 31611 21420 12195 18425 |
|22806 21202 20341 20696 21456 15851 13344 16939 |

CPU times: user 511 µs, sys: 0 ns, total: 511 µs
Wall time: 475 µs


In [130]:
# Changing Data Type
E = linalg.Matrix(K) 
F = linalg.Matrix(L) 

In [131]:
%%time
print(E@F)

|81867 12345 97391 86892 |
|82867 13267 11427 96776 |
|12527 15036 88577 91020 |
|12937 16208 12696 11371 |

CPU times: user 813 µs, sys: 0 ns, total: 813 µs
Wall time: 1.41 ms


IX. Pymatrix

In [132]:
!pip install pymatrix

  Created wheel for pymatrix: filename=pymatrix-3.0.1-cp36-none-any.whl size=7067 sha256=41327efdc488898dafdbda4d6e91641c751319885d1db9242d774ed758413e7f
  Stored in directory: /root/.cache/pip/wheels/7a/b5/9a/d5e6c01679e1a22385c2112e667314703a79fe7560a33f824c
Successfully built pymatrix


In [133]:
from pymatrix import matrix

In [134]:
A = matrix(X)
B = matrix(Y)

In [135]:
%%time
print(A*B)

1741968 2536047 1863610 1394572
1123711 1887410 1493488  788791
1321631 1647641 1426769  909406
1082589 1638529 1338240  810507
CPU times: user 498 µs, sys: 969 µs, total: 1.47 ms
Wall time: 1.55 ms


In [136]:
# Changing N Value
C = matrix(U)
D = matrix(V)

In [137]:
%%time
print(C*D)

1785161 2066644 2052930 1615890 1881700 1568936  846661 1048269
2754460 2520839 2577981 2247542 2719076 1605787 1472405 1560552
2023084 1826475 1796767 1137473 2115736  864259 1230269 1603023
1916034 1675327 1907385 1665524 1823832 1187624 1225676 1067248
2451892 1658709 1953031 2324864 2030310 1249589 1438451 1114459
3528284 3305970 3163650 2728300 3351610 2315535 1811483 2434469
3185363 3127996 2867473 2654045 3161196 2142059 1219570 1842523
2280625 2120251 2034148 2069679 2145635 1585113 1334458 1693992
CPU times: user 1.15 ms, sys: 15 µs, total: 1.17 ms
Wall time: 1.1 ms


In [138]:
# Changing Data Type
E = matrix(K)
F = matrix(L)

In [139]:
%%time
print(E*F)

 818679.5865281747 1234585.3816418373  973918.9836640868  868929.7026977197
 828679.2405935277 1326752.7291857116  1142772.503374862  967767.4920586946
1252739.4761699121 1503658.0729144425  885776.7961503561  910204.9261996413
1293781.9373831188 1620874.2669810983 1269688.0538017412  1137132.260547974
CPU times: user 0 ns, sys: 861 µs, total: 861 µs
Wall time: 1.26 ms


X. TensorFlow

In [140]:
import tensorflow as tf

In [141]:
%%time
print(tf.matmul(X, Y))

tf.Tensor(
[[1741968 2536047 1863610 1394572]
 [1123711 1887410 1493488  788791]
 [1321631 1647641 1426769  909406]
 [1082589 1638529 1338240  810507]], shape=(4, 4), dtype=int32)
CPU times: user 16.4 ms, sys: 13 ms, total: 29.4 ms
Wall time: 98.9 ms


In [142]:
# Changing N Value
%%time
print(tf.matmul(U, V))

tf.Tensor(
[[1785161 2066644 2052930 1615890 1881700 1568936  846661 1048269]
 [2754460 2520839 2577981 2247542 2719076 1605787 1472405 1560552]
 [2023084 1826475 1796767 1137473 2115736  864259 1230269 1603023]
 [1916034 1675327 1907385 1665524 1823832 1187624 1225676 1067248]
 [2451892 1658709 1953031 2324864 2030310 1249589 1438451 1114459]
 [3528284 3305970 3163650 2728300 3351610 2315535 1811483 2434469]
 [3185363 3127996 2867473 2654045 3161196 2142059 1219570 1842523]
 [2280625 2120251 2034148 2069679 2145635 1585113 1334458 1693992]], shape=(8, 8), dtype=int32)
CPU times: user 2.5 ms, sys: 0 ns, total: 2.5 ms
Wall time: 4.75 ms


In [143]:
# Changing Data Type
%%time
print(tf.matmul(K, L))

tf.Tensor(
[[ 818679.6  1234585.4   973919.    868929.7 ]
 [ 828679.25 1326752.8  1142772.5   967767.5 ]
 [1252739.5  1503658.    885776.75  910204.94]
 [1293782.   1620874.2  1269688.1  1137132.2 ]], shape=(4, 4), dtype=float32)
CPU times: user 25 ms, sys: 2.21 ms, total: 27.3 ms
Wall time: 43.3 ms
