In [19]:
import multiprocessing 
import os 
import time

In [35]:
import random
X = [random.choices(range(9,999), k=4) for _ in range(4)]
Y = [random.choices(range(9,999), k=4) for _ in range(4)]
result = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]

In [36]:
print(X)
print(Y)
print(result)

[[580, 534, 738, 339], [528, 493, 622, 446], [904, 11, 612, 273], [598, 482, 369, 651]]
[[941, 685, 520, 189], [833, 207, 56, 89], [775, 777, 382, 141], [550, 817, 183, 286]]
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [37]:
%%time
for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

print(result)

[[1749002, 1358227, 675457, 358158], [1634867, 1311407, 621390, 358927], [1484277, 1320082, 754439, 336205], [1608249, 1327984, 598043, 394135]]
CPU times: user 1.15 ms, sys: 0 ns, total: 1.15 ms
Wall time: 1.01 ms


In [38]:
%%time
def worker1(X, Y, result): 
  for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
  return result

def worker2(X, Y, result):
  for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
  return result
  
if __name__ == "__main__": 

  # creating processes 
  p1 = multiprocessing.Process(target=worker1) 
  p2 = multiprocessing.Process(target=worker2)

  # starting processes 
  p1.start() 
  p2.start()

  # wait until processes are finished 
  p1.join() 
  p2.join() 

  # both processes finished 
  print(worker1(X[:2],Y,[[0,0,0,0],[0,0,0,0]]))
  print(worker2(X[2:],Y,[[0,0,0,0],[0,0,0,0]]))
  print("Done!")

Process Process-5:
Traceback (most recent call last):
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
TypeError: worker2() missing 3 required positional arguments: 'X', 'Y', and 'result'
TypeError: worker1() missing 3 required positional arguments: 'X', 'Y', and 'result'


[[1749002, 1358227, 675457, 358158], [1634867, 1311407, 621390, 358927]]
[[1484277, 1320082, 754439, 336205], [1608249, 1327984, 598043, 394135]]
Done!
CPU times: user 13.2 ms, sys: 14.3 ms, total: 27.5 ms
Wall time: 63.3 ms


In [39]:
import numpy as np

In [40]:
A = np.array(X)
B = np.array(Y)

In [41]:
%%time
print(np.dot(A,B))

[[1749002 1358227  675457  358158]
 [1634867 1311407  621390  358927]
 [1484277 1320082  754439  336205]
 [1608249 1327984  598043  394135]]
CPU times: user 0 ns, sys: 796 µs, total: 796 µs
Wall time: 748 µs


In [42]:
from sympy import *

In [43]:
A = Matrix(X)
B = Matrix(Y)

In [44]:
A

Matrix([
[580, 534, 738, 339],
[528, 493, 622, 446],
[904,  11, 612, 273],
[598, 482, 369, 651]])

In [45]:
B

Matrix([
[941, 685, 520, 189],
[833, 207,  56,  89],
[775, 777, 382, 141],
[550, 817, 183, 286]])

In [48]:
%%time
print(A*B)

Matrix([[1749002, 1358227, 675457, 358158], [1634867, 1311407, 621390, 358927], [1484277, 1320082, 754439, 336205], [1608249, 1327984, 598043, 394135]])
CPU times: user 1.76 ms, sys: 978 µs, total: 2.74 ms
Wall time: 6.12 ms


In [49]:
import pandas as pd

In [50]:
A = pd.DataFrame(X)
B = pd.DataFrame(Y)

In [55]:
%%time
print(A.dot(B))

         0        1       2       3
0  1749002  1358227  675457  358158
1  1634867  1311407  621390  358927
2  1484277  1320082  754439  336205
3  1608249  1327984  598043  394135
CPU times: user 8.45 ms, sys: 1.05 ms, total: 9.5 ms
Wall time: 13.4 ms


In [56]:
import tensorflow as tf

In [58]:
%%time
print(tf.matmul(X, Y))

tf.Tensor(
[[1749002 1358227  675457  358158]
 [1634867 1311407  621390  358927]
 [1484277 1320082  754439  336205]
 [1608249 1327984  598043  394135]], shape=(4, 4), dtype=int32)
CPU times: user 2.72 ms, sys: 100 µs, total: 2.82 ms
Wall time: 19.6 ms


In [60]:
!pip install linalg

  Created wheel for linalg: filename=linalg-1.0.4-cp36-none-any.whl size=6294 sha256=e8ce23d5821e54e8ddc7e8ff4c0ba2105e84dcd77b29a0ec0c816878722386f5
  Stored in directory: /root/.cache/pip/wheels/a6/09/2b/ed39c10f756adfcf310484fda9ff8ca0f647fc08fb2171a76b
Successfully built linalg


In [61]:
import linalg

In [62]:
A = linalg.Matrix(X) 
B = linalg.Matrix(Y) 

In [63]:
%%time
print(A@B)

|17490 13582 67545 35815 |
|16348 13114 62139 35892 |
|14842 13200 75443 33620 |
|16082 13279 59804 39413 |

CPU times: user 183 µs, sys: 24 µs, total: 207 µs
Wall time: 168 µs


In [66]:
!pip install pymatrix

In [67]:
from pymatrix import matrix

In [68]:
A = matrix(X)
B = matrix(Y)

In [69]:
%%time
print(A*B)

1749002 1358227  675457  358158
1634867 1311407  621390  358927
1484277 1320082  754439  336205
1608249 1327984  598043  394135
CPU times: user 929 µs, sys: 0 ns, total: 929 µs
Wall time: 912 µs


In [70]:
from scipy import linalg

In [72]:
A = np.array(X)
B = np.array(Y)

In [74]:
%%time
print(A.dot(B))

[[1749002 1358227  675457  358158]
 [1634867 1311407  621390  358927]
 [1484277 1320082  754439  336205]
 [1608249 1327984  598043  394135]]
CPU times: user 716 µs, sys: 0 ns, total: 716 µs
Wall time: 741 µs


In [75]:
import numba
from numba import jit

In [103]:
@jit('void(int64[:,:],int64[:,:],int64[:,:])')
def numba_mul(matrix1,matrix2,rmatrix):
  for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
      for k in range(len(matrix2)):
        rmatrix[i][j] += matrix1[i][k] * matrix2[k][j]

In [105]:
matrix1 = np.array(X)
matrix2 = np.array(Y)
rmatrix = np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]])

In [106]:
%%time
numba_mul(matrix1,matrix2,rmatrix)
for r in rmatrix:
  print(r)

[1749002 1358227  675457  358158]
[1634867 1311407  621390  358927]
[1484277 1320082  754439  336205]
[1608249 1327984  598043  394135]
CPU times: user 2.4 ms, sys: 37 µs, total: 2.44 ms
Wall time: 2.39 ms


In [109]:
!pip install pycuda

     |████████████████████████████████| 1.6MB 5.5MB/s 
     |████████████████████████████████| 71kB 6.3MB/s 
     |████████████████████████████████| 481kB 19.0MB/s 
  Created wheel for pycuda: filename=pycuda-2020.1-cp36-cp36m-linux_x86_64.whl size=621123 sha256=13bdcc7c041d9c6463bda5096763ad6a85183d628859b39aa51a7bac8293d0dc
  Stored in directory: /root/.cache/pip/wheels/8f/78/d1/5bb826f81d9d490297a348d818ff3ee6dd6f2075b06dde6ea0
  Created wheel for pytools: filename=pytools-2021.1-py2.py3-none-any.whl size=60415 sha256=94c37c1bd6700bbd8d270217bc5931bb2b4303e293d2ee6a45c981591b731cf9
  Stored in directory: /root/.cache/pip/wheels/5d/85/10/7da05d77b47f2cb503e5c4185ba82187d0b6b6736b3c6641e0
  Created wheel for mako: filename=Mako-1.1.4-py2.py3-none-any.whl size=75675 sha256=b5124ffe1ffe75e5dd99318fbcf0b5c2e8cf841a79a6ed8699175818cc836aca
  Stored in directory: /root/.cache/pip/wheels/ad/10/d3/aeb26e20d19045e2a68e5d3cbb57432e11b5d9c92c99f98d47
Successfully built pycuda pytools mako


In [110]:
import pycuda.autoinit
from pycuda import driver, compiler, gpuarray

RuntimeError: ignored